# Generated by Django 4.1.7 on 2023-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_command_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='total',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
